"""LangGraph orchestration layer for SupportFlow.

Constructs a stateful workflow graph that orchestrates the existing
SupportFlow capabilities:  classification, RAG retrieval, tool execution,
approval checking, and response generation.

LangGraph is the ORCHESTRATOR — all business logic, validation,
authorization, and database operations remain in the existing service
modules (tools.py, approval.py, kb.py, rag.py, llm.py).
"""

from __future__ import annotations

import json
import os
from typing import TypedDict

# pyrefly: ignore [missing-import]
from dotenv import load_dotenv
# pyrefly: ignore [missing-import]
from groq import Groq
# pyrefly: ignore [missing-import]
from langgraph.graph import StateGraph, START, END

# Reuse existing SupportFlow capabilities — NO duplication
from app.llm import classify_ticket, _execute_tool_call, AVAILABLE_TOOLS
from app.kb import search_knowledge_base
from app.rag import answer_with_knowledge_base, RAG_SIMILARITY_THRESHOLD

load_dotenv()

# ── Configuration ─────────────────────────────────────────────────────
MAX_TOOL_ITERATIONS = 5
GROQ_MODEL = "openai/gpt-oss-120b"

# Categories that indicate the customer is asking a knowledge/policy
# question rather than requesting a specific action on an order.
KNOWLEDGE_CATEGORIES = {
    "General Inquiry",
    "Shipping Inquiry",
    "Policy Question",
    "general inquiry",
    "shipping inquiry",
    "policy question",
}

# Categories that typically require tool execution
ACTION_CATEGORIES = {
    "Order Issue",
    "Refund Request",
    "Billing",
    "Technical Support",
    "order issue",
    "refund request",
    "billing",
    "technical support",
}


# ═══════════════════════════════════════════════════════════════════════
# GRAPH STATE
# ═══════════════════════════════════════════════════════════════════════

class SupportFlowState(TypedDict):
    """Typed state flowing through the LangGraph workflow.

    Contains only serializable values needed for orchestration.
    Durable state remains in PostgreSQL.
    """
    customer_message: str
    authenticated_customer_id: int
    ticket_id: int | None
    classification: dict | None
    retrieved_documents: list[dict] | None
    rag_answer: str | None
    tool_calls: list[dict]
    tool_iterations: int
    approval_status: str | None
    final_response: str
    error: str | None
    execution_log: list[str]


# ═══════════════════════════════════════════════════════════════════════
# NODE FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════

def classify_node(state: SupportFlowState) -> dict:
    """Classifies the customer message into category/priority/sentiment.

    Reuses: classify_ticket() from app.llm
    """
    log = list(state.get("execution_log", []))
    log.append("→ ENTERED: classify_node")

    try:
        classification = classify_ticket(state["customer_message"])
        log.append(f"  classification: {classification}")
        return {
            "classification": classification,
            "execution_log": log,
        }
    except Exception as err:
        log.append(f"  ERROR in classify_node: {err}")
        return {
            "classification": None,
            "error": f"Classification failed: {err}",
            "execution_log": log,
        }


def retrieve_knowledge_node(state: SupportFlowState) -> dict:
    """Retrieves relevant policy documents and generates a grounded answer.

    Reuses: answer_with_knowledge_base() from app.rag
    (which internally calls search_knowledge_base() from app.kb)
    """
    log = list(state.get("execution_log", []))
    log.append("→ ENTERED: retrieve_knowledge_node")

    try:
        rag_result = answer_with_knowledge_base(state["customer_message"])

        retrieved_docs = rag_result.get("retrieved_documents", [])
        relevant = rag_result.get("relevant_context", False)

        log.append(f"  relevant_context: {relevant}")
        log.append(f"  retrieved_documents: {len(retrieved_docs)}")
        for doc in retrieved_docs:
            log.append(f"    - \"{doc['title']}\" (sim={doc['cosine_similarity']:.4f})")

        if relevant:
            log.append(f"  rag_answer generated by LLM")
            return {
                "retrieved_documents": retrieved_docs,
                "rag_answer": rag_result["answer"],
                "final_response": rag_result["answer"],
                "execution_log": log,
            }
        else:
            log.append("  no relevant policy found — will generate generic response")
            return {
                "retrieved_documents": retrieved_docs,
                "rag_answer": None,
                "final_response": rag_result["answer"],
                "execution_log": log,
            }

    except Exception as err:
        log.append(f"  ERROR in retrieve_knowledge_node: {err}")
        return {
            "error": f"RAG retrieval failed: {err}",
            "execution_log": log,
        }


def tool_execution_node(state: SupportFlowState) -> dict:
    """Sends the message to Groq with tool schemas and executes requested tools.

    Reuses:
    - Groq tool-calling API (same model + tool schemas from app.llm)
    - _execute_tool_call() from app.llm for validation/authorization/execution
    """
    log = list(state.get("execution_log", []))
    tool_calls = list(state.get("tool_calls", []))
    iterations = state.get("tool_iterations", 0)

    log.append(f"→ ENTERED: tool_execution_node (iteration {iterations + 1})")

    # Guard: iteration limit
    if iterations >= MAX_TOOL_ITERATIONS:
        log.append("  ERROR: max tool iterations reached")
        return {
            "error": "Maximum tool-call iterations reached",
            "tool_iterations": iterations,
            "execution_log": log,
        }

    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        log.append("  ERROR: GROQ_API_KEY not set")
        return {"error": "GROQ_API_KEY not set", "execution_log": log}

    client = Groq(api_key=api_key)

    # Build messages from accumulated context
    system_prompt = (
        "You are a helpful customer support AI assistant for SupportFlow. "
        "Answer customer questions politely and concisely. "
        "If the customer asks about an order status and provides an order ID, "
        "use the 'get_order_status' tool to look it up. "
        "If the customer wants a replacement for a damaged or defective order, "
        "first check the order status with 'get_order_status', then ALWAYS use "
        "'create_replacement_request' to attempt the replacement. "
        "If the customer requests a refund for an order, use the 'issue_refund' tool "
        "with the order_id and requested amount. "
        "If the 'issue_refund' tool returns status 'PENDING_APPROVAL', inform the "
        "customer clearly that their refund request has been submitted for human "
        "approval and has NOT been issued yet. Never claim a refund was completed "
        "if approval is pending. "
        "You must NOT decide whether an order is eligible or whether approval is required — "
        "the backend will make that determination. Always call the tool and "
        "relay the backend result to the customer. "
        "Do not invent or guess order details. "
        "Do not fabricate tool results."
    )

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": state["customer_message"]},
    ]

    # Replay previous tool interactions so the LLM has full context
    for tc in tool_calls:
        # Simulate the assistant's tool_call message
        messages.append({
            "role": "assistant",
            "content": None,
            "tool_calls": [{
                "id": tc.get("tool_call_id", f"call_{tc['iteration']}"),
                "type": "function",
                "function": {
                    "name": tc["tool_name"],
                    "arguments": json.dumps(tc["tool_args"]),
                },
            }],
        })
        # Simulate the tool response
        messages.append({
            "role": "tool",
            "tool_call_id": tc.get("tool_call_id", f"call_{tc['iteration']}"),
            "content": json.dumps(tc["tool_result"]),
        })

    # Call Groq with tools
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=messages,
            tools=AVAILABLE_TOOLS,
            tool_choice="auto",
            temperature=0.0,
        )
    except Exception as err:
        log.append(f"  ERROR: Groq API failed: {err}")
        return {"error": f"Groq API failed: {err}", "execution_log": log}

    response_message = response.choices[0].message

    # ── No tool calls → LLM produced final response ──────────────
    if not response_message.tool_calls:
        final = response_message.content or ""
        log.append(f"  LLM produced final response (no more tools)")
        return {
            "final_response": final,
            "tool_iterations": iterations + 1,
            "execution_log": log,
        }

    # ── Process tool calls ────────────────────────────────────────
    approval_status = state.get("approval_status")

    for tc in response_message.tool_calls:
        tool_name = tc.function.name
        try:
            tool_args = json.loads(tc.function.arguments)
        except Exception:
            tool_args = {"raw": tc.function.arguments}

        log.append(f"  tool requested: {tool_name}({tool_args})")

        # Dispatch through existing backend validation + auth + execution
        execution = _execute_tool_call(
            tool_name, tool_args, state["authenticated_customer_id"]
        )

        log.append(f"    validation: {'✅' if execution['validation_passed'] else '❌'}")
        if execution["authorization_passed"] is not None:
            log.append(f"    authorization: {'✅' if execution['authorization_passed'] else '❌'}")
        log.append(f"    executed: {'✅' if execution['backend_executed'] else '❌'}")

        tool_result = execution["tool_result"]

        # Check for approval-required status
        if isinstance(tool_result, dict) and tool_result.get("status") == "PENDING_APPROVAL":
            approval_status = "PENDING_APPROVAL"
            log.append(f"    → APPROVAL REQUIRED (approval_id={tool_result.get('approval_id')})")

        tool_calls.append({
            "iteration": iterations + 1,
            "tool_name": tool_name,
            "tool_args": tool_args,
            "tool_call_id": tc.id,
            "validation_passed": execution["validation_passed"],
            "authorization_passed": execution["authorization_passed"],
            "backend_executed": execution["backend_executed"],
            "tool_result": tool_result,
        })

    return {
        "tool_calls": tool_calls,
        "tool_iterations": iterations + 1,
        "approval_status": approval_status,
        "execution_log": log,
    }


def approval_check_node(state: SupportFlowState) -> dict:
    """Records that an approval is pending. Does NOT fake/bypass approval.

    In a real system this node would wait for the human decision.
    For this milestone it captures the state and lets the response
    generator inform the customer.

    Reuses: approval status already set by tool execution results.
    """
    log = list(state.get("execution_log", []))
    log.append("→ ENTERED: approval_check_node")
    log.append(f"  approval_status: {state.get('approval_status')}")

    return {"execution_log": log}


def generate_response_node(state: SupportFlowState) -> dict:
    """Generates the final customer-facing response.

    If a response was already produced (by RAG or tool execution),
    it is used directly. Otherwise, calls Groq for a final summary.

    Reuses: Groq LLM for response generation.
    """
    log = list(state.get("execution_log", []))
    log.append("→ ENTERED: generate_response_node")

    # If we already have a final response (from RAG or tool loop), use it
    existing = state.get("final_response", "")
    if existing:
        log.append("  using existing final_response")
        return {"execution_log": log}

    # Generate from accumulated context
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        return {
            "final_response": "I'm sorry, I'm unable to process your request at this time.",
            "execution_log": log,
        }

    client = Groq(api_key=api_key)

    context_parts = [f"Customer message: {state['customer_message']}"]
    if state.get("classification"):
        context_parts.append(f"Classification: {state['classification']}")
    if state.get("error"):
        context_parts.append(f"Error: {state['error']}")

    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a helpful customer support assistant. "
                        "Generate a helpful, professional response to the customer. "
                        "If there was an error, explain it politely."
                    ),
                },
                {"role": "user", "content": "\n".join(context_parts)},
            ],
            temperature=0.0,
        )
        final = response.choices[0].message.content or ""
        log.append("  generated final response via LLM")
        return {"final_response": final.strip(), "execution_log": log}

    except Exception as err:
        log.append(f"  ERROR generating response: {err}")
        return {
            "final_response": "I apologize, but I encountered an issue processing your request.",
            "execution_log": log,
        }


def error_node(state: SupportFlowState) -> dict:
    """Captures error state and produces a safe customer-facing response."""
    log = list(state.get("execution_log", []))
    log.append(f"→ ENTERED: error_node (error: {state.get('error')})")

    return {
        "final_response": (
            "I apologize, but I encountered an issue processing your request. "
            "Please try again or contact a human support agent."
        ),
        "execution_log": log,
    }


# ═══════════════════════════════════════════════════════════════════════
# CONDITIONAL EDGES (routing functions)
# ═══════════════════════════════════════════════════════════════════════

def route_after_classify(state: SupportFlowState) -> str:
    """Routes after classification based on the detected category.

    Knowledge/policy questions → RAG retrieval
    Action-oriented categories → tool execution
    Errors → error node
    """
    if state.get("error"):
        return "error_node"

    classification = state.get("classification", {})
    category = (classification.get("category", "") or "").strip()

    # Check if this is a knowledge/policy question
    # Use case-insensitive comparison
    category_lower = category.lower()
    if any(kc.lower() in category_lower for kc in KNOWLEDGE_CATEGORIES):
        return "retrieve_knowledge_node"

    # Default: assume action-oriented → tool execution
    return "tool_execution_node"


def route_after_tool(state: SupportFlowState) -> str:
    """Routes after tool execution.

    - If approval is required → approval_check_node
    - If LLM already produced a final response → generate_response_node
    - If more tool calls needed and under limit → tool_execution_node (loop)
    - Otherwise → generate_response_node
    """
    if state.get("error"):
        return "error_node"

    # If approval was triggered, route through approval check
    if state.get("approval_status") == "PENDING_APPROVAL":
        return "approval_check_node"

    # If we got a final response from the tool node, we're done
    if state.get("final_response"):
        return "generate_response_node"

    # If under iteration limit and no final response yet, loop back
    if state.get("tool_iterations", 0) < MAX_TOOL_ITERATIONS:
        return "tool_execution_node"

    # Safety: hit iteration limit
    return "generate_response_node"


def route_after_approval(state: SupportFlowState) -> str:
    """Routes after approval check → always to response generation."""
    return "generate_response_node"


# ═══════════════════════════════════════════════════════════════════════
# GRAPH CONSTRUCTION
# ═══════════════════════════════════════════════════════════════════════

def build_supportflow_graph():
    """Constructs and compiles the SupportFlow LangGraph workflow.

    Graph structure:
        START → classify_node
          → [route_after_classify]
             ├── retrieve_knowledge_node → generate_response_node → END
             ├── tool_execution_node
             │     → [route_after_tool]
             │        ├── tool_execution_node (loop, max 5)
             │        ├── approval_check_node → generate_response_node → END
             │        ├── error_node → END
             │        └── generate_response_node → END
             └── error_node → END
    """
    graph = StateGraph(SupportFlowState)

    # ── Add nodes ─────────────────────────────────────────────────
    graph.add_node("classify_node", classify_node)
    graph.add_node("retrieve_knowledge_node", retrieve_knowledge_node)
    graph.add_node("tool_execution_node", tool_execution_node)
    graph.add_node("approval_check_node", approval_check_node)
    graph.add_node("generate_response_node", generate_response_node)
    graph.add_node("error_node", error_node)

    # ── Add edges ─────────────────────────────────────────────────
    # START → classify
    graph.add_edge(START, "classify_node")

    # classify → conditional routing
    graph.add_conditional_edges(
        "classify_node",
        route_after_classify,
        {
            "retrieve_knowledge_node": "retrieve_knowledge_node",
            "tool_execution_node": "tool_execution_node",
            "error_node": "error_node",
        },
    )

    # knowledge retrieval → response
    graph.add_edge("retrieve_knowledge_node", "generate_response_node")

    # tool execution → conditional routing
    graph.add_conditional_edges(
        "tool_execution_node",
        route_after_tool,
        {
            "tool_execution_node": "tool_execution_node",
            "approval_check_node": "approval_check_node",
            "generate_response_node": "generate_response_node",
            "error_node": "error_node",
        },
    )

    # approval check → response
    graph.add_conditional_edges(
        "approval_check_node",
        route_after_approval,
        {
            "generate_response_node": "generate_response_node",
        },
    )

    # response → END
    graph.add_edge("generate_response_node", END)

    # error → END
    graph.add_edge("error_node", END)

    return graph.compile()


# Compiled graph singleton
_compiled_graph = None


def _get_graph():
    """Returns the compiled graph singleton."""
    global _compiled_graph
    if _compiled_graph is None:
        _compiled_graph = build_supportflow_graph()
    return _compiled_graph


# ═══════════════════════════════════════════════════════════════════════
# ENTRY FUNCTION
# ═══════════════════════════════════════════════════════════════════════

def run_supportflow(
    customer_message: str,
    authenticated_customer_id: int,
    ticket_id: int | None = None,
) -> SupportFlowState:
    """Executes the SupportFlow LangGraph workflow.

    This is the main entry point for running a customer message through
    the full orchestration pipeline.  It is independent of FastAPI and
    can be tested standalone.

    Args:
        customer_message:         The customer's natural-language message.
        authenticated_customer_id: Trusted customer identity.
        ticket_id:                Optional ticket ID for context.

    Returns:
        SupportFlowState: Final workflow state with all accumulated context.
    """
    initial_state: SupportFlowState = {
        "customer_message": customer_message,
        "authenticated_customer_id": authenticated_customer_id,
        "ticket_id": ticket_id,
        "classification": None,
        "retrieved_documents": None,
        "rag_answer": None,
        "tool_calls": [],
        "tool_iterations": 0,
        "approval_status": None,
        "final_response": "",
        "error": None,
        "execution_log": [],
    }

    graph = _get_graph()
    result = graph.invoke(initial_state)
    return result
